### ISSUE TITLE
learning-logs: list of `Activity` under a specific `Title` should be unique

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/dev-helpers#3]
## Acceptance

- [ ] Output produces unique `Activity` under each `Title`.
- [ ] Output produces unique `Notes` next to each `Title` or `Activity`.

## Tasks

- [ ] Ensure no `Activity` can appear more than once under the same `Title`.
  - [ ] Add test.
- [ ] Review the logic for the `Notes` field too.
  - [ ] Add test, if necessary.

## Analysis

Example of flawed output with duplicated line (superfluous spacing is besides the point and could be tackled in another issue):

![2021-11-17_20-58](https://user-images.githubusercontent.com/32682903/142343868-653bd0b8-5178-4549-95f0-8acf4deba4c2.png)
