### ISSUE TITLE
learning-logs: Implement `-y` argument to get output for a specific year

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/dev-helpers#4]
## Acceptance

* [ ] The `learning-logs` tool supports a `-y` argument on the command line to specify a year for which data should be outputted.

## Tasks

* [ ] Make it so that the `-y` argument accepts an integer parameter.
* [ ] Add relevant tests.
