### ISSUE TITLE
learning-logs: Implement `-m` argument to get output for a specific month

### ISSUE THREAD

**Issue by sglavoie** [sglavoie/dev-helpers#5]
## Acceptance

* [ ] The `learning-logs` tool supports a `-m` argument on the command line to specify a month for which data should be outputted.
* [ ] Should work when combined with the `-y` argument. See #4 
	* [ ] If the `-y` argument is absent, use the most recent year **and** the relevant month.
	* [ ] If the `-y` argument is passed, use data for the year corresponding to the parameter value **and** the relevant month.

## Tasks

* [ ] Make it so that the `-m` argument accepts an integer parameter.
* [ ] Add relevant tests.
